[project]
name = "translator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jeffrey Li", email = "jeffrey.li@woojar.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.12",
    "deep-translator>=1.11.4",
    "requests>=2.32",
]

[dependency-groups]
dev = [
    "pytest>=8.3",
]

[project.scripts]
translator = "translator:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]
